name: PHP CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # chạy khi có push vào nhánh main
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_mysql, dom, curl
        coverage: none

    - name: Install dependencies (composer)
      run: |
        if [ -f composer.json ]; then
          composer install --no-progress --prefer-dist
        fi

    - name: Run tests (PHPUnit)
      run: |
        if [ -f phpunit.xml ] || [ -f phpunit.xml.dist ]; then
          ./vendor/bin/phpunit
        else
          echo "Không có test để chạy"
        fi

    - name: Deploy to production server (optional)
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd src
          git pull origin main
          composer install --no-dev
          php artisan migrate
